use training secret in github action

diff --git a/.github/workflows/basic-check.yml b/.github/workflows/basic-check.yml
--- a/.github/workflows/basic-check.yml
+++ b/.github/workflows/basic-check.yml
@@ -18,3 +18,11 @@ jobs:
 
       - name: Print message
         run: echo "GitHub Actions is working correctly"
+              - name: Check secret exists
+        run: |
+          if [ -z "${{ secrets.TRAINING_SECRET }}" ]; then
+            echo "Secret is missing"
+            exit 1
+          else
+            echo "Secret exists"
+          fi
